# See http://about.travis-ci.org/docs/user/build-configuration/
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language:
  - scala

scala:
  - 2.10.5
  - 2.11.7

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - ximagination80@gmail.com

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
  - pip install --user codecov

  - git clone https://github.com/ximagination80/Comparator.git
  - cd Comparator
  - sbt test
  - sbt publishLocal

  - git clone https://github.com/playframework/anorm.git
  - cd anorm
  - sbt publishLocal -feature

addons:
  postgresql: "9.4"

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - codecov